//
// Created by gensh on 18/10/2025.
//

#ifndef DPIBULLETHELLRE_SALLESPROJECTILE1FACTORY_H
#define DPIBULLETHELLRE_SALLESPROJECTILE1FACTORY_H



class SallesProjectile1Factory {

};



#endif //DPIBULLETHELLRE_SALLESPROJECTILE1FACTORY_H
